# 01_data_prep.ipynb

## Setup

In [1]:
import os
import sys
from pathlib import Path

# Mount colab
if True:
    if not os.path.exists('/content/drive'):
        from google.colab import drive
        drive.mount('/content/drive')

PROJECT_ROOT: Path = Path("/content/drive/MyDrive/python/projects/nlp_projects/med/biomedical-extraction-pipeline")
os.chdir(PROJECT_ROOT)

# Add the PROJECT_ROOT directory to the Python path to import modules
if str(PROJECT_ROOT) in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(f"ℹ️ Current Python version: {sys.version}")

Mounted at /content/drive
ℹ️ Current Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [2]:
# Install reqs (NOTE: restart after this)
if True:
    %pip install -r {"requirements/01_data_prep.txt"}

Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 3)) (2.2.2)
Requirement already satisfied: numpy==2.0.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 4)) (2.0.2)
Requirement already satisfied: scikit-learn==1.6.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 5)) (1.6.1)
Requirement already satisfied: scipy==1.16.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 6)) (1.16.3)
Requirement already satisfied: matplotlib==3.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 7)) (3.10.0)
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 8)) (0.13.2)
Requirement already satisfied: tqdm==4.67.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 9)) (4.67.3)
Requirement already satisfied: python-dotenv==1.2.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements/00_core.txt (line 10)) (1.2.2)
Collecting datasets==3.6.0 (from -r requirements/01_data_prep.txt (line 6))
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Collecting bioc==2.1 (from -r requirements/01_data_prep.txt (line 8))
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Collecting huggingface_hub==1.16.1 (from -r requirements/01_data_prep.txt (line 9))
  Downloading huggingface_hub-1.16.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pyarrow==18.1.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements/01_data_prep.txt (line 10)) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements/00_core.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements/00_core.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->-r requirements/00_core.txt (line 3)) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements/00_core.txt (line 5)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.6.1->-r requirements/00_core.txt (line 5)) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.0->-r requirements/00_core.txt (line 7)) (3.3.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (3.29.2)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (6.0.3)
Requirement already satisfied: lxml>=4.6.3 in /usr/local/lib/python3.12/dist-packages (from bioc==2.1->-r requirements/01_data_prep.txt (line 8)) (6.1.1)
Collecting jsonlines>=1.2.0 (from bioc==2.1->-r requirements/01_data_prep.txt (line 8))
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc==2.1->-r requirements/01_data_prep.txt (line 8))
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting docopt (from bioc==2.1->-r requirements/01_data_prep.txt (line 8))
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (0.28.1)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (0.16.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonlines>=1.2.0->bioc==2.1->-r requirements/01_data_prep.txt (line 8)) (26.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2->-r requirements/00_core.txt (line 3)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (2.5.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (0.0.4)
Collecting sortedcontainers (from intervaltree->bioc==2.1->-r requirements/01_data_prep.txt (line 8))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0->-r requirements/01_data_prep.txt (line 6)) (1.24.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface_hub==1.16.1->-r requirements/01_data_prep.txt (line 9)) (0.1.2)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 10.7 MB/s eta 0:00:00
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading huggingface_hub-1.16.1-py3-none-any.whl (668 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.2/668.2 kB 23.3 MB/s eta 0:00:00
Downloading jsonlines-4.0.0-py3-none-any.whl (8.7 kB)
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=c9c9280d97f5338fed0d4052d13ad9e70290eb868a12591b952d684c80d8500d
  Stored in directory: /root/.cache/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built docopt
Installing collected packages: sortedcontainers, docopt, jsonlines, intervaltree, bioc, huggingface_hub, datasets
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.18.0
    Uninstalling huggingface_hub-1.18.0:
      Successfully uninstalled huggingface_hub-1.18.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed bioc-2.1 datasets-3.6.0 docopt-0.6.2 huggingface_hub-1.16.1 intervaltree-3.2.1 jsonlines-4.0.0 sortedcontainers-2.4.0

In [48]:
# --- src ---
from src.config import load_configs
from src.utils import dynamic_module_reloader, seed_everything
from src.data_utils.preprocessing import (
    ensure_validation_split,
    flatten_bc5cdr,
    create_labeled_candidate_pairs
    )

# --- other ---
import pandas as pd
import torch
from dotenv import load_dotenv
from pprint import pprint
from datasets import load_dataset, DatasetDict, Dataset

MODULES_TO_RELOAD = [
    "src",
    "src.config",
    "src.utils",
    "src.data_utils",
    "src.data_utils.preprocessing"
]

dynamic_module_reloader(modules=MODULES_TO_RELOAD, verbose=1)
config = load_configs()
load_dotenv()
seed_everything(config.env.seed)
pprint(config.to_dict())

# Constants
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {DEVICE}")

Reloaded: src
Reloaded: src.config
Reloaded: src.utils
Reloaded: src.data_utils
Reloaded: src.data_utils.preprocessing
✅ Seed set to 42
{'data': {'data_folder': PosixPath('data/documents'),
          'dataset_name': 'bigbio/bc5cdr',
          'flattened_dataset_name': PosixPath('data/processed/bc5cdr_flattened'),
          'relations_dataset_path': PosixPath('data/processed/bc5cdr_relations')},
 'env': {'seed': 42},
 'model': {'ner_label_names': ['O',
                               'B-Chemical',
                               'I-Chemical',
                               'B-Disease',
                               'I-Disease'],
           'ner_model_checkpoint': 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract',
           'ner_model_name': 'BiomedNLP-BiomedBERT-base-uncased-ner-abstract-bc5cdr-LoRA-v1.1'},
 'tracking': {'project': 'Biomed-IE',
              'tracker': 'trackio',
              'trackio_space_id': 'Francesco-A/nlp-tracking'}}
Using device: cpu

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

## Data

### Download the dataset (bigbio/BC5CDR)

In [4]:
# Load the bigbio BC5CDR dataset
dataset = load_dataset(config.data.dataset_name, trust_remote_code=True, token=os.environ["HF_TOKEN"])
ensure_validation_split(dataset)

README.md:   0%|          | 0.00/1.68k [00:00<?, ?B/s]

bc5cdr.py:   0%|          | 0.00/13.9k [00:00<?, ?B/s]

bigbiohub.py:   0%|          | 0.00/19.3k [00:00<?, ?B/s]

CDR_Data.zip:   0%|          | 0.00/20.4M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Dataset has a validation split already: no action performed.

DatasetDict({
    train: Dataset({
        features: ['passages'],
        num_rows: 500
    })
    test: Dataset({
        features: ['passages'],
        num_rows: 500
    })
    validation: Dataset({
        features: ['passages'],
        num_rows: 500
    })
})

In [ ]:
# Show feature schema and a single example
print(f"Dataset shape: {dataset.shape}")
print("\nFeature schema (train):\n", dataset["train"].features)
print("\nTrain keys:", list(dataset["train"][0].keys()))
if False:
    print("\nExample :")
    pprint(dataset["train"][0]["passages"])

Dataset shape: {'train': (500, 1), 'test': (500, 1), 'validation': (500, 1)}

Feature schema (train):
 {'passages': [{'document_id': Value(dtype='string', id=None), 'type': Value(dtype='string', id=None), 'text': Value(dtype='string', id=None), 'entities': [{'id': Value(dtype='string', id=None), 'offsets': [[Value(dtype='int32', id=None)]], 'text': [Value(dtype='string', id=None)], 'type': Value(dtype='string', id=None), 'normalized': [{'db_name': Value(dtype='string', id=None), 'db_id': Value(dtype='string', id=None)}]}], 'relations': [{'id': Value(dtype='string', id=None), 'type': Value(dtype='string', id=None), 'arg1_id': Value(dtype='string', id=None), 'arg2_id': Value(dtype='string', id=None)}]}]}

Train keys: ['passages']

### Inspect dataset structure

In [61]:
# Expand a single record to see the nested structure
sample = dataset["train"][0]
passages_df = pd.json_normalize(sample['passages'])
print("Sample passages structure:")
print(passages_df.head().to_markdown())
print("\nColumns:", passages_df.columns.tolist())

# Flatten all passages from the entire train split
all_passages = []
for record in dataset["train"]:
    all_passages.extend(record['passages'])

passages_df_full = pd.json_normalize(all_passages)
print(f"\nFull passages DataFrame shape: {passages_df_full.shape}")
print("\nFirst few rows:")
print(passages_df_full.head().to_markdown())
print("\nData types:")
print(passages_df_full.dtypes)

Sample passages structure:
|    |   document_id | type     | text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | entities                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | relations                                                                 |
|---:|--------------:|:---------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------|
|  0 |        227508 | title    | Naloxone reverses the antihypertensive effect of clonidine.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | [{'id': '0', 'offsets': [[0, 8]], 'text': ['Naloxone'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]}, {'id': '1', 'offsets': [[49, 58]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | [{'id': 'R0', 'type': 'CID', 'arg1_id': 'D008750', 'arg2_id': 'D007022'}] |
|  1 |        227508 | abstract | In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone. | [{'id': '2', 'offsets': [[93, 105]], 'text': ['hypertensive'], 'type': 'Disease', 'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]}, {'id': '3', 'offsets': [[181, 190]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}, {'id': '4', 'offsets': [[244, 252]], 'text': ['nalozone'], 'type': 'Chemical', 'normalized': []}, {'id': '5', 'offsets': [[274, 285]], 'text': ['hypotensive'], 'type': 'Disease', 'normalized': [{'db_name': 'MESH', 'db_id': 'D007022'}]}, {'id': '6', 'offsets': [[306, 322]], 'text': ['alpha-methyldopa'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D008750'}]}, {'id': '7', 'offsets': [[354, 362]], 'text': ['naloxone'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]}, {'id': '8', 'offsets': [[364, 372]], 'text': ['Naloxone'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]}, {'id': '9', 'offsets': [[469, 481]], 'text': ['hypertensive'], 'type': 'Disease', 'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]}, {'id': '10', 'offsets': [[487, 496]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}, {'id': '11', 'offsets': [[563, 576]], 'text': ['[3H]-naloxone'], 'type': 'Chemical', 'normalized': []}, {'id': '12', 'offsets': [[589, 597]], 'text': ['naloxone'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]}, {'id': '13', 'offsets': [[637, 646]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}, {'id': '14', 'offsets': [[671, 695]], 'text': ['[3H]-dihydroergocryptine'], 'type': 'Chemical', 'normalized': []}, {'id': '15', 'offsets': [[750, 762]], 'text': ['hypertensive'], 'type': 'Disease', 'normalized': [{'db_name': 'MESH', 'db_id': 'D006973'}]}, {'id': '16', 'offsets': [[865, 873]], 'text': ['naloxone'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D009270'}]}, {'id': '17', 'offsets': [[878, 887]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}, {'id': '18', 'offsets': [[1026, 1035]], 'text': ['clonidine'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D003000'}]}, {'id': '19', 'offsets': [[1039, 1055]], 'text': ['alpha-methyldopa'], 'type': 'Chemical', 'normalized': [{'db_name': 'MESH', 'db_id': 'D008750'}]}] | [{'id': 'R0', 'type': 'CID', 'arg1_id': 'D008750', 'arg2_id': 'D007022'}] |

Columns: ['document_id', 'type', 'text', 'entities', 'relations']

Full passages DataFrame shape: (1000, 5)

First few rows:
|    |   document_id | type     | text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | entities                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | relations                                                                 |

In [ ]:
if True:
    # Check the structure of entities and relations
    display(pd.json_normalize(passages_df_full['entities']))
    display(pd.json_normalize(passages_df_full['relations']))

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,"{'id': '0', 'offsets': [[0, 8]], 'text': ['Nal...","{'id': '1', 'offsets': [[49, 58]], 'text': ['c...",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"{'id': '2', 'offsets': [[93, 105]], 'text': ['...","{'id': '3', 'offsets': [[181, 190]], 'text': [...","{'id': '4', 'offsets': [[244, 252]], 'text': [...","{'id': '5', 'offsets': [[274, 285]], 'text': [...","{'id': '6', 'offsets': [[306, 322]], 'text': [...","{'id': '7', 'offsets': [[354, 362]], 'text': [...","{'id': '8', 'offsets': [[364, 372]], 'text': [...","{'id': '9', 'offsets': [[469, 481]], 'text': [...","{'id': '10', 'offsets': [[487, 496]], 'text': ...","{'id': '11', 'offsets': [[563, 576]], 'text': ...",...,None,None,None,None,None,None,None,None,None,None
2,"{'id': '0', 'offsets': [[0, 9]], 'text': ['Lid...","{'id': '1', 'offsets': [[18, 34]], 'text': ['c...",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"{'id': '2', 'offsets': [[90, 99]], 'text': ['l...","{'id': '3', 'offsets': [[142, 152]], 'text': [...","{'id': '4', 'offsets': [[331, 347]], 'text': [...","{'id': '5', 'offsets': [[409, 418]], 'text': [...",None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,"{'id': '0', 'offsets': [[0, 13]], 'text': ['Su...","{'id': '1', 'offsets': [[41, 55]], 'text': ['f...",None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"{'id': '2', 'offsets': [[143, 154]], 'text': [...","{'id': '3', 'offsets': [[163, 178]], 'text': [...","{'id': '4', 'offsets': [[558, 573]], 'text': [...","{'id': '5', 'offsets': [[614, 625]], 'text': [...","{'id': '6', 'offsets': [[799, 822]], 'text': [...","{'id': '7', 'offsets': [[838, 849]], 'text': [...","{'id': '8', 'offsets': [[858, 873]], 'text': [...","{'id': '9', 'offsets': [[994, 1001]], 'text': ...",None,None,...,None,None,None,None,None,None,None,None,None,None
996,"{'id': '0', 'offsets': [[45, 53]], 'text': ['m...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
997,"{'id': '1', 'offsets': [[145, 152]], 'text': [...","{'id': '2', 'offsets': [[165, 176]], 'text': [...","{'id': '3', 'offsets': [[181, 194]], 'text': [...","{'id': '4', 'offsets': [[212, 220]], 'text': [...","{'id': '5', 'offsets': [[281, 289]], 'text': [...","{'id': '6', 'offsets': [[356, 364]], 'text': [...","{'id': '7', 'offsets': [[412, 423]], 'text': [...","{'id': '8', 'offsets': [[447, 458]], 'text': [...","{'id': '9', 'offsets': [[467, 474]], 'text': [...","{'id': '10', 'offsets': [[512, 525]], 'text': ...",...,None,None,None,None,None,None,None,None,None,None
998,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
999,"{'id': '0', 'offsets': [[296, 307]], 'text': [...","{'id': '1', 'offsets': [[324, 340]], 'text': [...","{'id': '2', 'offsets': [[417, 428]], 'text': [...","{'id': '3', 'offsets': [[465, 473]], 'text': [...","{'id': '4', 'offsets': [[583, 594]], 'text': [...","{'id': '5', 'offsets': [[699, 710]], 'text': [...","{'id': '6', 'offsets': [[719, 732]], 'text': [...","{'id': '7', 'offsets': [[879, 890]], 'text': [...","{'id': '8', 'offsets': [[912, 923]], 'text': [...","{'id': '9', 'offsets': [[934, 945]], 'text': [...",...,None,None,None,None,None,None,None,None,None,None

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00875...",None,None,None,None,None,None,None,None,None,None,None,None,None
1,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00875...",None,None,None,None,None,None,None,None,None,None,None,None,None
2,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00801...",None,None,None,None,None,None,None,None,None,None,None,None,None
3,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00801...",None,None,None,None,None,None,None,None,None,None,None,None,None
4,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D01339...",None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D01398...","{'id': 'R1', 'type': 'CID', 'arg1_id': 'D01398...",None,None,None,None,None,None,None,None,None,None,None,None
996,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D01260...","{'id': 'R1', 'type': 'CID', 'arg1_id': 'D00351...",None,None,None,None,None,None,None,None,None,None,None,None
997,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D01260...","{'id': 'R1', 'type': 'CID', 'arg1_id': 'D00351...",None,None,None,None,None,None,None,None,None,None,None,None
998,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00105...","{'id': 'R1', 'type': 'CID', 'arg1_id': 'D00105...",None,None,None,None,None,None,None,None,None,None,None,None
999,"{'id': 'R0', 'type': 'CID', 'arg1_id': 'D00105...","{'id': 'R1', 'type': 'CID', 'arg1_id': 'D00105...",None,None,None,None,None,None,None,None,None,None,None,None

### Generate flattened dataset

In [5]:
# Flatten the passages using the utility function across all the splits
flattened_dataset = DatasetDict({split: flatten_bc5cdr(dataset[split]) for split in dataset.keys()})
flattened_dataset

DatasetDict({
    train: Dataset({
        features: ['document_id', 'text', 'entities', 'relations'],
        num_rows: 500
    })
    test: Dataset({
        features: ['document_id', 'text', 'entities', 'relations'],
        num_rows: 500
    })
    validation: Dataset({
        features: ['document_id', 'text', 'entities', 'relations'],
        num_rows: 500
    })
})

### Generate labeled relationship dataset

In [72]:
# Create the labeled relation extraction dataset from the flattened train split
relations_dataset = flattened_dataset.copy()
for key in relations_dataset.keys():
    # Create the labeled relation extraction dataset from the flattened train split
    temp_df = relations_dataset[key].to_pandas()
    all_relation_candidates = []
    for _, row in temp_df.iterrows():
        all_relation_candidates.extend(create_labeled_candidate_pairs(row))

    relations_dataset[key] = Dataset.from_pandas(pd.DataFrame(all_relation_candidates))

relations_dataset = DatasetDict(relations_dataset)
relations_dataset

DatasetDict({
    train: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label'],
        num_rows: 5515
    })
    test: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label'],
        num_rows: 5528
    })
    validation: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label'],
        num_rows: 5317
    })
})

In [56]:
# Check head of train split to make sure it looks good
print(
    relations_dataset["train"]
    .to_pandas()
    .head(10)
    .to_markdown()
)

|    |   document_id | chemical         | disease          | chemical_id   | disease_id   | masked_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   label |
|---:|--------------:|:-----------------|:-----------------|:--------------|:-------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|
|  0 |        227508 | naloxone         | hypertensive     | D009270       | D006973      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                        |       0 |
|  1 |        227508 | naloxone         | hypotensive      | D009270       | D007022      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                  |       0 |
|  2 |        227508 | clonidine        | hypertensive     | D003000       | D006973      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone. |       0 |
|  3 |        227508 | clonidine        | hypotensive      | D003000       | D007022      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                           |       0 |
|  4 |        227508 | nalozone         | hypertensive     |               | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                      |       0 |
|  5 |        227508 | nalozone         | hypotensive      |               | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                |       0 |
|  6 |        227508 | alpha-methyldopa | hypertensive     | D008750       | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                             |       0 |
|  7 |        227508 | alpha-methyldopa | hypotensive      | D008750       | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                                       |       1 |
|  8 |        354896 | lidocaine        | cardiac asystole | D008012       | D006323      | <chemical> Lidocaine </chemical>-induced <disease> cardiac asystole </disease>. Intravenous administration of a single 50-mg bolus of <chemical> lidocaine </chemical> in a 67-year-old man resulted in profound depression of the activity of the sinoatrial and atrioventricular nodal pacemakers. The patient had no apparent associated conditions which might have predisposed him to the development of bradyarrhythmias; and, thus, this probably represented a true idiosyncrasy to <chemical> lidocaine </chemical>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |       1 |
|  9 |        354896 | lidocaine        | depression       | D008012       | D003866      | <chemical> Lidocaine </chemical>-induced cardiac asystole. Intravenous administration of a single 50-mg bolus of <chemical> lidocaine </chemical> in a 67-year-old man resulted in profound <disease> depression </disease> of the activity of the sinoatrial and atrioventricular nodal pacemakers. The patient had no apparent associated conditions which might have predisposed him to the development of bradyarrhythmias; and, thus, this probably represented a true idiosyncrasy to <chemical> lidocaine </chemical>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |       0 |

In [62]:
if True:
    # Assert that both tags are in each masked_text
    for key in relations_dataset.keys():
        subset = relations_dataset[key].to_pandas()
        assert not subset.empty, 'No candidates generated'
        missing_mask = (~subset['masked_text'].str.contains('<chemical>', case=False)) | (~subset['masked_text'].str.contains('<disease>', case=False))
        if missing_mask.any():
            missing = subset[missing_mask]
            raise AssertionError(f"Some rows are missing tags: {len(missing)} rows in split {key}. Examples: {missing.head(5)['document_id'].tolist()}")
        # All checks passed
        print(f'All masked_text entries contain both <chemical> and <disease> tags in split {key}.')

All masked_text entries contain both <chemical> and <disease> tags in split train.
All masked_text entries contain both <chemical> and <disease> tags in split test.
All masked_text entries contain both <chemical> and <disease> tags in split validation.

### Save processed data

In [ ]:
# Save the flattened dataset to disk
flattened_dataset.save_to_disk(config.data.flattened_dataset_path)
relations_dataset.save_to_disk(config.data.relations_dataset_path)

print(f"Saved flattened dataset to {config.data.flattened_dataset_path}")
print(f"Saved relation extraction dataset to {config.data.relations_dataset_path}")

Saving the dataset (0/1 shards):   0%|          | 0/5515 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5528 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/5317 [00:00<?, ? examples/s]

Saved flattened dataset to data/processed/bc5cdr_flattened
Saved relation extraction dataset to data/processed/bc5cdr_relations

## Requirements (full snapshot)

In [76]:
if True:
    !pip freeze > snapshots/01_data_prep.txt