# 03_weak_supervision.ipynb

## Setup

In [ ]:
import os
import sys
from pathlib import Path

IS_KAGGLE: bool = False

if IS_KAGGLE:
    # git clone repo
    from kaggle_secrets import UserSecretsClient
    token = UserSecretsClient().get_secret("GITHUB_TOKEN")
    username = UserSecretsClient().get_secret("GITHUB_USERNAME")
    !git clone https://{username}:{token}@github.com/{username}/biomed-ie-distill-xai.git
    PROJECT_ROOT: Path = Path("/kaggle/working/biomed-ie-distill-xai")
else:
    # Mount colab
    if not os.path.exists('/content/drive'):
        from google.colab import drive
        drive.mount('/content/drive')
    PROJECT_ROOT = Path("/content/drive/MyDrive/python/projects/nlp_projects/med/biomedical-extraction-pipeline")

os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(f"ℹ️ Current Python version: {sys.version}")

ℹ️ Current Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [ ]:
if True:
    # =====================================================================
    # STEP 1: CLEAN AND INITIALIZE HARDWARE ENVIRONMENT
    # =====================================================================
    !pip uninstall -y vllm llama-cpp-python
    !pip install -U uv
    !uv self update

    # =====================================================================
    # STEP 2: ENGINE SELECTION SWITCHBOARD
    # Set the engine you want to use to True, and the other to False
    # =====================================================================

    RUN_VLLM_SETUP = False
    RUN_LLAMACPP_SETUP = True

    if RUN_VLLM_SETUP:
        # -----------------------------------------------------------------
        # VLLM ENGINE PATH (Requires A100 / L4 GPU)
        # Forces the environment up to CUDA 13.0 for vLLM compatibility
        # -----------------------------------------------------------------
        !pip uninstall -y torch torchvision torchaudio
        
        !uv pip install --system \
        --torch-backend cu130 \
        --index-strategy unsafe-best-match \
        --extra-index-url https://wheels.vllm.ai/nightly/cu130 \
        -r requirements/03_weak_supervision.txt

    if RUN_LLAMACPP_SETUP:
        # -----------------------------------------------------------------
        # LLAMA-CPP ENGINE PATH (Instant Precompiled GPU Wheel)
        # -----------------------------------------------------------------
        
        !uv pip install --system \
            -r requirements/03_weak_supervision.txt \
            llama-cpp-python \
            --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu125

WARNING: Skipping vllm as it is not installed.
WARNING: Skipping llama-cpp-python as it is not installed.
Collecting uv
  Downloading uv-0.11.26-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.11.26-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.3/26.3 MB 84.3 MB/s eta 0:00:00:00:0100:01
Installing collected packages: uv
Successfully installed uv-0.11.26
info: Checking for updates...
success: You're already on version v0.11.26 of uv (the latest version).
Google Colab (Python 3.12) detected. Routing to cu125 wheels.
Using Python 3.12.13 environment at: /usr
Resolved 114 packages in 50.28s
Prepared 13 packages in 52.97s
Uninstalled 4 packages in 741ms
Installed 13 packages in 139ms
 + bitsandbytes==0.49.2
 + diskcache==5.6.3
 + genson==1.3.0
 + groq==1.5.0
 - huggingface-hub==1.20.1
 + huggingface-hub==0.36.2
 + instructor==1.15.4
 - jiter==0.15.0
 + jiter==0.14.0
 + jsonpath-ng==1.8.0
 + llama-cpp-python==0.3.32
 + outlines==1.3.1
 + outlines-core==0.2.14
 - torchao==0.10.0
 + torchao==0.17.0
 - transformers==5.12.1
 + transformers==4.57.6

In [2]:
import llama_cpp

if llama_cpp.llama_supports_gpu_offload():
    print("✅ Success: GPU acceleration backend is enabled!")
else:
    print("❌ Fail: Running on CPU only. Reinstall with proper GPU flags.")

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 14912 MiB):
  Device 0: Tesla T4, compute capability 7.5, VMM: yes, VRAM: 14912 MiB

✅ Success: GPU acceleration backend is enabled!

In [ ]:
# --- src ---
from src.config import load_configs
from src.utils import (
    dynamic_module_reloader,
    seed_everything,
    setup_kaggle_environment,
    )
from src.structured_extraction.generator import get_response
from src.structured_extraction.prompts import SYSTEM_PROMPT

# --- other ---
import numpy as np
import pandas as pd
import torch
from dotenv import load_dotenv
from pprint import pprint
from datasets import DatasetDict

MODULES_TO_RELOAD = [
    "src",
    "src.config",
    "src.utils",
    "src.model_utils",
    "src.structured_extraction.outlines"
]
dynamic_module_reloader(modules=MODULES_TO_RELOAD, verbose=1)

config = load_configs()
load_dotenv()
seed_everything(config.env.seed)
device: str = 'cuda' if torch.cuda.is_available() else 'cpu'
smoke_test: bool = False
model = (
    config.model.client_tagger_checkpoint 
    if device == 'cpu' 
    else config.model.local_tagger_checkpoint_large
)
suffix = model.lower().split("/")[-1] + ".parquet"
setup_kaggle_environment(
    config = config,
    suffix = suffix,
    kaggle_input_dir = "/kaggle/input/datasets/francescoalbanesephd/biomed-ie-distill-xai/",
    is_kaggle = IS_KAGGLE,
)

if smoke_test:
    pass

print("\n\t--- Notebook settings ---")
print(f"Using device: {device}")
print(f"smoke_test mode: {smoke_test}")
print("General configs:\n")
pprint(config.to_dict())

Reloaded: src
Reloaded: src.config
Reloaded: src.utils
✅ Seed set to 42
{'data': {'data_folder': PosixPath('data/documents'),
          'dataset_name': 'bigbio/bc5cdr',
          'flattened_dataset_name': PosixPath('data/processed/bc5cdr_flattened'),
          'relations_dataset_name': PosixPath('data/processed/bc5cdr_relations'),
          'structured_checkpoint_file': PosixPath('data/checkpoints/structured_data'),
          'structured_file': PosixPath('data/processed/structured_data')},
 'env': {'seed': 42},
 'model': {'client_tagger_checkpoint': 'groq/qwen/qwen3-32b',
           'local_tagger_checkpoint_large': 'Qwen/Qwen2.5-32B-Instruct',
           'local_tagger_checkpoint_medium': 'Qwen/Qwen2.5-14B-Instruct',
           'local_tagger_checkpoint_small': 'Qwen/Qwen2.5-7B-Instruct',
           'ner_label_names': ['O',
                               'B-Chemical',
                               'I-Chemical',
                               'B-Disease',
                               'I-Disease'],
           'ner_model_checkpoint': 'microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract',
           'ner_model_name': 'BiomedNLP-BiomedBERT-base-uncased-ner-abstract-bc5cdr-LoRA-v1.1',
           'relation_model_checkpoint': 'microsoft/BiomedNLP-BiomedBERT-base-uncased-relation',
           'relation_model_name': 'BiomedNLP-BiomedBERT-base-uncased-relation-bc5cdr-LoRA-v1.1'},
 'tracking': {'project': 'Biomed-IE',
              'tracker': 'trackio',
              'trackio_space_id': 'Francesco-A/nlp-tracking'}}

	--- Notebook settings ---
Using device: cuda
smoke_test mode: False

In [4]:
!nvidia-smi

Thu Jul  2 16:35:00 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## Data

In [5]:
flattened_dataset = DatasetDict.load_from_disk(config.data.flattened_dataset_name)
relationship_dataset = DatasetDict.load_from_disk(config.data.relations_dataset_name)
    
if True:
    relationship_dataset = relationship_dataset.map(
        lambda example: {
            "pair_id": f"{example['document_id']}_{example['chemical_id']}_{example['disease_id']}"
        },
        keep_in_memory = IS_KAGGLE
    )

relationship_dataset

DatasetDict({
    train: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label', 'pair_id'],
        num_rows: 5515
    })
    test: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label', 'pair_id'],
        num_rows: 5528
    })
    validation: Dataset({
        features: ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id', 'masked_text', 'label', 'pair_id'],
        num_rows: 5317
    })
})

In [ ]:
for split in flattened_dataset.keys():
    print(f"\nProcessing split: {split}") 
    structured_checkpoint_file = (config.data.structured_checkpoint_file / suffix.replace(".parquet", f"-{split}.parquet"))
    
    structured_df = get_response(
        id_col="document_id",
        text_col="text",
        model_checkpoint=config.model.local_tagger_checkpoint_small,
        df_to_structure=flattened_dataset,
        df_exploded_reference=relationship_dataset,
        instruction=SYSTEM_PROMPT,
        structured_checkpoint_file=structured_checkpoint_file,
        structured_file= None,
        is_macro=True,
        max_tokens="auto",
        checkpoint_steps=1,
        sleep_time=15,
        model_source = "llama_cpp",
        dataset_split=split,
        n_rows_to_process=2,
        drop_invalid_from_checkpoint=True,
        verbose=False,
    )

ℹ️ Using local model via Outlines & llama-cpp: Qwen/Qwen2.5-14B-Instruct-GGUF

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

qwen2.5-14b-instruct-q4_k_m-00001-of-000(…):   0%|          | 0.00/3.99G [00:00<?, ?B/s]

qwen2.5-14b-instruct-q4_k_m-00002-of-000(…):   0%|          | 0.00/3.99G [00:00<?, ?B/s]

qwen2.5-14b-instruct-q4_k_m-00003-of-000(…):   0%|          | 0.00/1.01G [00:00<?, ?B/s]

Model path: /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-14B-Instruct-GGUF/snapshots/b466e1f8c07172155743e8e1307507d8a4f91fbd/qwen2.5-14b-instruct-q4_k_m-00001-of-00003.gguf
ℹ️ Final processed/structured file not found. Checking for checkpoint...
Starting full instructor/outlines pipeline...
Total items to process: 4

Generating Structured Data:   0%|          | 0/2 [00:00<?, ?it/s]

============================================================
Batch 1 | rows 0 to 1
============================================================

  0%|          | 0/2 [00:00<?, ?it/s]

⏳ Processing row 0 | document_id=227508
------------------------------------------------------------
Macro mode detected. Candidate count: 8
Max tokens set to: 2912
Candidate list:
- Chemical: naloxone | Disease: hypertensive
- Chemical: naloxone | Disease: hypotensive
- Chemical: clonidine | Disease: hypertensive
- Chemical: clonidine | Disease: hypotensive
- Chemical: nalozone | Disease: hypertensive
- Chemical: nalozone | Disease: hypotensive
- Chemical: alpha-methyldopa | Disease: hypertensive
- Chemical: alpha-methyldopa | Disease: hypotensive
[DEBUG] Outlines kwargs:
{'temperature': 0.0, 'max_tokens': 2912}
[DEBUG] Response type:
<class 'str'>
[DEBUG] Raw output:
{"relationships": [{"chemical": "naloxone", "disease": "hypertensive", "chain_of_thought": "Pair: [naloxone] + [hypertensive] | Observation: Naloxone does not directly affect blood pressure or heart rate in spontaneously hypertensive rats.", "weak_label": "0"}, {"chemical": "naloxone", "disease": "hypotensive", "chain_of_thought": "Pair: [naloxone] + [hypotensive] | Observation: Naloxone reverses the hypotensive effect of clonidine and partially reverses the hypotensive effect of alpha-methyldopa.", "weak_label": "3"}, {"chemical": "clonidine", "disease": "hypertensive", "chain_of_thought": "Pair: [clonidine] + [hypertensive] | Observation: Clonidine decreases blood pressure and heart rate in spontaneously hypertensive rats, indicating it treats hypertension.", "weak_label": "2"}, {"chemical": "clonidine", "disease": "hypotensive", "chain_of_thought": "Pair: [clonidine] + [hypotensive] | Observation: Clonidine causes a hypotensive effect, which is the intended therapeutic action.", "weak_label": "2"}, {"chemical": "nalozone", "disease": "hypertensive", "chain_of_thought": "Pair: [nalozone] + [hypertensive] | Observation: Nalozone is not mentioned in the text as affecting hypertension.", "weak_label": "0"}, {"chemical": "nalozone", "disease": "hypotensive", "chain_of_thought": "Pair: [nalozone] + [hypotensive] | Observation: Nalozone is not mentioned in the text as affecting hypotension.", "weak_label": "0"}, {"chemical": "alpha-methyldopa", "disease": "hypertensive", "chain_of_thought": "Pair: [alpha-methyldopa] + [hypertensive] | Observation: Alpha-methyldopa is used to treat hypertension, as indicated by its partial reversal by naloxone.", "weak_label": "2"}, {"chemical": "alpha-methyldopa", "disease": "hypotensive", "chain_of_thought": "Pair: [alpha-methyldopa] + [hypotensive] | Observation: Alpha-methyldopa causes a hypotensive effect, which is the intended therapeutic action.", "weak_label": "2"}]}
⏳ Processing row 1 | document_id=354896
------------------------------------------------------------
Macro mode detected. Candidate count: 3
Max tokens set to: 1412
Candidate list:
- Chemical: lidocaine | Disease: cardiac asystole
- Chemical: lidocaine | Disease: depression
- Chemical: lidocaine | Disease: bradyarrhythmias
[DEBUG] Outlines kwargs:
{'temperature': 0.0, 'max_tokens': 1412}
[DEBUG] Response type:
<class 'str'>
[DEBUG] Raw output:
{"relationships": [{"chemical": "lidocaine", "disease": "cardiac asystole", "chain_of_thought": "Pair: lidocaine + cardiac asystole | Observation: Lidocaine caused cardiac asystole in the patient.", "weak_label": "1"}, {"chemical": "lidocaine", "disease": "depression", "chain_of_thought": "Pair: lidocaine + depression | Observation: Lidocaine caused depression of the activity of the sinoatrial and atrioventricular nodal pacemakers, but 'depression' here refers to a mechanical reduction in pacemaker activity, not a clinical condition, so no direct relationship exists.", "weak_label": "0"}, {"chemical": "lidocaine", "disease": "bradyarrhythmias", "chain_of_thought": "Pair: lidocaine + bradyarrhythmias | Observation: Lidocaine resulted in bradyarrhythmias in the patient.", "weak_label": "1"}]}

============================================================
Batch 2 | rows 2 to 3
============================================================

  0%|          | 0/2 [00:00<?, ?it/s]

⏳ Processing row 2 | document_id=435349
------------------------------------------------------------
Macro mode detected. Candidate count: 2
Max tokens set to: 1112
Candidate list:
- Chemical: suxamethonium | Disease: fasciculations
- Chemical: suxamethonium | Disease: tetanic
[DEBUG] Outlines kwargs:
{'temperature': 0.0, 'max_tokens': 1112}
[DEBUG] Response type:
<class 'str'>
[DEBUG] Raw output:
{"relationships": [{"chemical": "suxamethonium", "disease": "fasciculations", "chain_of_thought": "Pair: suxamethonium + fasciculations | Observation: Suxamethonium causes fasciculations in a dose-dependent manner.", "weak_label": "1"}, {"chemical": "suxamethonium", "disease": "tetanic", "chain_of_thought": "Pair: suxamethonium + tetanic | Observation: The text does not establish a direct relationship between suxamethonium and tetanic.", "weak_label": "0"}]}
⏳ Processing row 3 | document_id=603022
------------------------------------------------------------
Macro mode detected. Candidate count: 3
Max tokens set to: 1412
Candidate list:
- Chemical: galanthamine hydrobromide | Disease: overdosage
- Chemical: scopolamine | Disease: overdosage
- Chemical: physostigmine | Disease: overdosage
[DEBUG] Outlines kwargs:
{'temperature': 0.0, 'max_tokens': 1412}
[DEBUG] Response type:
<class 'str'>
[DEBUG] Raw output:
{"relationships": [{"chemical": "galanthamine hydrobromide", "disease": "overdosage", "chain_of_thought": "Pair: [galanthamine hydrobromide] + [overdosage] | Observation: The text does not explicitly state that galanthamine hydrobromide causes or treats overdosage, but rather it is used to reverse the effects of scopolamine.", "weak_label": "0"}, {"chemical": "scopolamine", "disease": "overdosage", "chain_of_thought": "Pair: [scopolamine] + [overdosage] | Observation: The text explicitly states that scopolamine causes overdosage effects.", "weak_label": "1"}, {"chemical": "physostigmine", "disease": "overdosage", "chain_of_thought": "Pair: [physostigmine] + [overdosage] | Observation: The text does not explicitly state that physostigmine treats or causes overdosage, but rather it is used for comparison with galanthamine hydrobromide.", "weak_label": "0"}]}
✅ Merged structured data with original DataFrame. Resulting DataFrame has 5515 rows.

In [11]:
# 14B
cols = ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id',
       'masked_text', 'pair_id', 'chain_of_thought', 'label', 'weak_label',
       'extraction_status']
print(structured_df.query("extraction_status == 'SUCCESS'")[cols].to_markdown())

|    |   document_id | chemical                  | disease          | chemical_id   | disease_id   | masked_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | pair_id                | chain_of_thought                                                                                                                                                                                                                                                                           |   label |   weak_label | extraction_status   |
|---:|--------------:|:--------------------------|:-----------------|:--------------|:-------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|-------------:|:--------------------|
|  0 |        227508 | naloxone                  | hypertensive     | D009270       | D006973      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                        | 227508_D009270_D006973 | Pair: [naloxone] + [hypertensive] | Observation: Naloxone does not directly affect blood pressure or heart rate in spontaneously hypertensive rats.                                                                                                                                        |       0 |            0 | SUCCESS             |
|  1 |        227508 | naloxone                  | hypotensive      | D009270       | D007022      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                  | 227508_D009270_D007022 | Pair: [naloxone] + [hypotensive] | Observation: Naloxone reverses the hypotensive effect of clonidine and partially reverses the hypotensive effect of alpha-methyldopa.                                                                                                                   |       0 |            3 | SUCCESS             |
|  2 |        227508 | clonidine                 | hypertensive     | D003000       | D006973      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone. | 227508_D003000_D006973 | Pair: [clonidine] + [hypertensive] | Observation: Clonidine decreases blood pressure and heart rate in spontaneously hypertensive rats, indicating it treats hypertension.                                                                                                                 |       0 |            2 | SUCCESS             |
|  3 |        227508 | clonidine                 | hypotensive      | D003000       | D007022      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                           | 227508_D003000_D007022 | Pair: [clonidine] + [hypotensive] | Observation: Clonidine causes a hypotensive effect, which is the intended therapeutic action.                                                                                                                                                          |       0 |            2 | SUCCESS             |
|  4 |        227508 | nalozone                  | hypertensive     |               | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                      | 227508_None_D006973    | Pair: [nalozone] + [hypertensive] | Observation: Nalozone is not mentioned in the text as affecting hypertension.                                                                                                                                                                          |       0 |            0 | SUCCESS             |
|  5 |        227508 | nalozone                  | hypotensive      |               | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                | 227508_None_D007022    | Pair: [nalozone] + [hypotensive] | Observation: Nalozone is not mentioned in the text as affecting hypotension.                                                                                                                                                                            |       0 |            0 | SUCCESS             |
|  6 |        227508 | alpha-methyldopa          | hypertensive     | D008750       | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                             | 227508_D008750_D006973 | Pair: [alpha-methyldopa] + [hypertensive] | Observation: Alpha-methyldopa is used to treat hypertension, as indicated by its partial reversal by naloxone.                                                                                                                                 |       0 |            2 | SUCCESS             |
|  7 |        227508 | alpha-methyldopa          | hypotensive      | D008750       | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                                       | 227508_D008750_D007022 | Pair: [alpha-methyldopa] + [hypotensive] | Observation: Alpha-methyldopa causes a hypotensive effect, which is the intended therapeutic action.                                                                                                                                            |       1 |            2 | SUCCESS             |
|  8 |        354896 | lidocaine                 | cardiac asystole | D008012       | D006323      | <chemical> Lidocaine </chemical>-induced <disease> cardiac asystole </disease>. Intravenous administration of a single 50-mg bolus of <chemical> lidocaine </chemical> in a 67-year-old man resulted in profound depression of the activity of the sinoatrial and atrioventricular nodal pacemakers. The patient had no apparent associated conditions which might have predisposed him to the development of bradyarrhythmias; and, thus, this probably represented a true idiosyncrasy to <chemical> lidocaine </chemical>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 354896_D008012_D006323 | Pair: lidocaine + cardiac asystole | Observation: Lidocaine caused cardiac asystole in the patient.                                                                                                                                                                                        |       1 |            1 | SUCCESS             |

In [ ]:
# 7B
cols = ['document_id', 'chemical', 'disease', 'chemical_id', 'disease_id',
       'masked_text', 'pair_id', 'chain_of_thought', 'label', 'weak_label',
       'extraction_status']
print(structured_df.query("extraction_status == 'SUCCESS'")[cols].to_markdown())

|    |   document_id | chemical                  | disease          | chemical_id   | disease_id   | masked_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | pair_id                | chain_of_thought                                                                                                                                                                                         |   label |   weak_label | extraction_status   |
|---:|--------------:|:--------------------------|:-----------------|:--------------|:-------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------:|-------------:|:--------------------|
|  0 |        227508 | naloxone                  | hypertensive     | D009270       | D006973      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                        | 227508_D009270_D006973 | Pair: naloxone + hypertensive | Observation: Naloxone reverses the antihypertensive effect of clonidine.                                                                                                 |       0 |            3 | SUCCESS             |
|  1 |        227508 | naloxone                  | hypotensive      | D009270       | D007022      | <chemical> Naloxone </chemical> reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by <chemical> naloxone </chemical>. <chemical> Naloxone </chemical> alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and <chemical> naloxone </chemical>, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As <chemical> naloxone </chemical> and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                  | 227508_D009270_D007022 | Pair: naloxone + hypotensive | Observation: Naloxone reverses the antihypertensive effect of clonidine, which is a hypotensive effect.                                                                   |       0 |            1 | SUCCESS             |
|  2 |        227508 | clonidine                 | hypertensive     | D003000       | D006973      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone. | 227508_D003000_D006973 | Pair: clonidine + hypertensive | Observation: Clonidine decreases blood pressure and heart rate in unanesthetized, spontaneously hypertensive rats.                                                      |       0 |            2 | SUCCESS             |
|  3 |        227508 | clonidine                 | hypotensive      | D003000       | D007022      | Naloxone reverses the antihypertensive effect of <chemical> clonidine </chemical>. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous <chemical> clonidine </chemical>, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats <chemical> clonidine </chemical>, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence <chemical> clonidine </chemical>-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and <chemical> clonidine </chemical> do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by <chemical> clonidine </chemical> or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                           | 227508_D003000_D007022 | Pair: clonidine + hypotensive | Observation: Clonidine has a hypotensive effect in unanesthetized, spontaneously hypertensive rats.                                                                      |       0 |            0 | SUCCESS             |
|  4 |        227508 | nalozone                  | hypertensive     |               | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                      | 227508_None_D006973    | Pair: nalozone + hypertensive | Observation: Naloxone alone did not affect either blood pressure or heart rate.                                                                                          |       0 |            0 | SUCCESS             |
|  5 |        227508 | nalozone                  | hypotensive      |               | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by <chemical> nalozone </chemical>, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of <chemical> [3H]-naloxone </chemical> (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of <chemical> [3H]-dihydroergocryptine </chemical> (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                | 227508_None_D007022    | Pair: nalozone + hypotensive | Observation: Naloxone alone did not affect either blood pressure or heart rate.                                                                                           |       0 |            0 | SUCCESS             |
|  6 |        227508 | alpha-methyldopa          | hypertensive     | D008750       | D006973      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously <disease> hypertensive </disease> rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously <disease> hypertensive </disease> rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously <disease> hypertensive </disease> rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                             | 227508_D008750_D006973 | Pair: alpha-methyldopa + hypertensive | Observation: The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone.                                                       |       0 |            1 | SUCCESS             |
|  7 |        227508 | alpha-methyldopa          | hypotensive      | D008750       | D007022      | Naloxone reverses the antihypertensive effect of clonidine. In unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The <disease> hypotensive </disease> effect of 100 mg/kg <chemical> alpha-methyldopa </chemical> was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or <chemical> alpha-methyldopa </chemical> and the possible role of the opiate in the central control of sympathetic tone.                                                                                                                                       | 227508_D008750_D007022 | Pair: alpha-methyldopa + hypotensive | Observation: The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone.                                                        |       1 |            1 | SUCCESS             |
|  8 |        354896 | lidocaine                 | cardiac asystole | D008012       | D006323      | <chemical> Lidocaine </chemical>-induced <disease> cardiac asystole </disease>. Intravenous administration of a single 50-mg bolus of <chemical> lidocaine </chemical> in a 67-year-old man resulted in profound depression of the activity of the sinoatrial and atrioventricular nodal pacemakers. The patient had no apparent associated conditions which might have predisposed him to the development of bradyarrhythmias; and, thus, this probably represented a true idiosyncrasy to <chemical> lidocaine </chemical>.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 354896_D008012_D006323 | Pair: lidocaine + cardiac asystole | Observation: Lidocaine-induced cardiac asystole.                                                                                                                    |       1 |            1 | SUCCESS             |

In [7]:
checkpoint_df = pd.read_parquet("data/checkpoints/structured_data/qwen3_32b.parquet").sort_values("document_id", ascending=False)

display(checkpoint_df)
display(relationship_dataset["train"].to_pandas().head(100))

,document_id,extraction_status,chemical,disease,chain_of_thought,weak_label
1151,9869257,SUCCESS,scopolamine,amnesia,Scopolamine induces amnesia as a non-selective...,1
1152,9869257,SUCCESS,s-(-)-et-126,amnesia,S-(-)-ET-126 induces amnesia as an M1-selectiv...,1
1149,9869257,SUCCESS,acetylcholine,amnesia,Acetylcholine is described as a neurotransmitt...,0
1150,9869257,SUCCESS,pg-9,amnesia,PG-9 prevents amnesia induced by antimuscarini...,2
1148,9855119,FAILED: Error code: 429 - {'error': {'message'...,None,None,None,None
...,...,...,...,...,...,...
433,10193204,SUCCESS,tetrandrine,blood coagulation,Tetrandrine shows no anticoagulation activity ...,0
432,10193204,SUCCESS,tetrandrine,platelet aggregation,Tetrandrine dose-dependently inhibits human pl...,2
431,10193204,SUCCESS,tetrandrine,thrombosis,Tetrandrine inhibits experimental thrombosis i...,2
445,10193204,SUCCESS,acetylsalicylic acid,blood coagulation,ASA does not affect anticoagulation tests (APT...,0
440,10193204,SUCCESS,epinephrine,thrombosis,Epinephrine is used as an inducer of thrombosi...,0

,document_id,chemical,disease,chemical_id,disease_id,masked_text,label,pair_id
0,227508,naloxone,hypertensive,D009270,D006973,<chemical> Naloxone </chemical> reverses the a...,0,227508_D009270_D006973
1,227508,naloxone,hypotensive,D009270,D007022,<chemical> Naloxone </chemical> reverses the a...,0,227508_D009270_D007022
2,227508,clonidine,hypertensive,D003000,D006973,Naloxone reverses the antihypertensive effect ...,0,227508_D003000_D006973
3,227508,clonidine,hypotensive,D003000,D007022,Naloxone reverses the antihypertensive effect ...,0,227508_D003000_D007022
4,227508,nalozone,hypertensive,None,D006973,Naloxone reverses the antihypertensive effect ...,0,227508_None_D006973
...,...,...,...,...,...,...,...,...
95,2632720,deoxycorticosterone,hypertension,D003900,D006973,Arterial <disease> hypertension </disease> as ...,0,2632720_D003900_D006973
96,2632720,deoxycorticosterone,cushing's syndrome,D003900,D003480,Arterial hypertension as a complication of pro...,0,2632720_D003900_D003480
97,2632720,11-deoxycortisol,hypertension,D003350,D006973,Arterial <disease> hypertension </disease> as ...,0,2632720_D003350_D006973
98,2632720,11-deoxycortisol,cushing's syndrome,D003350,D003480,Arterial hypertension as a complication of pro...,0,2632720_D003350_D003480
99,2632720,aldosterone,hypertension,D000450,D006973,Arterial <disease> hypertension </disease> as ...,0,2632720_D000450_D006973

In [8]:
checkpoint_df.query("extraction_status != 'SUCCESS'")
checkpoint_df.query("document_id == '227508'")

,document_id,extraction_status,chemical,disease,chain_of_thought,weak_label
107,227508,SUCCESS,naloxone,hypertensive,Naloxone reverses the antihypertensive effect ...,3
108,227508,SUCCESS,naloxone,hypotensive,"Hypotensive is a physiological effect, not a c...",0
114,227508,SUCCESS,alpha-methyldopa,hypotensive,"Hypotensive is a physiological effect, not a c...",0
113,227508,SUCCESS,alpha-methyldopa,hypertensive,"Alpha-methyldopa is an antihypertensive agent,...",2
112,227508,SUCCESS,nalozone,hypotensive,"Hypotensive is a physiological effect, not a c...",0
111,227508,SUCCESS,nalozone,hypertensive,Nalozone (likely a typo for naloxone) reverses...,3
109,227508,SUCCESS,clonidine,hypertensive,"Clonidine is an antihypertensive agent, direct...",2
110,227508,SUCCESS,clonidine,hypotensive,"Hypotensive is a physiological effect, not a c...",0

In [9]:
subset = ['document_id', 'chemical', 'disease', 'pair_id', 'extraction_status', 'chain_of_thought', 'weak_label', 'label'] # 'masked_text' 
df_final_eval = pd.merge(
    relationship_dataset["train"].to_pandas(), # Your original evaluation dataframe with the 'label' column
    checkpoint_df,
    on=['document_id', 'chemical', 'disease'],
    how='left'
)

print(df_final_eval[subset].dropna().to_markdown())

|     |   document_id | chemical                                      | disease                                       | pair_id                  | extraction_status   | chain_of_thought                                                                                                                                                                                                                |   weak_label |   label |
|----:|--------------:|:----------------------------------------------|:----------------------------------------------|:-------------------------|:--------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------:|--------:|
|   0 |        227508 | naloxone                                      | hypertensive                                  | 227508_D009270_D006973   | SUCCESS             | Naloxone reverses the antihypertensive effect of clonidine, indicating active antagonism of the therapeutic action.                                                                                                             |            3 |       0 |
|   1 |        227508 | naloxone                                      | hypotensive                                   | 227508_D009270_D007022   | SUCCESS             | Hypotensive is a physiological effect, not a clinical disease, so no direct relation applies.                                                                                                                                   |            0 |       0 |
|   2 |        227508 | clonidine                                     | hypertensive                                  | 227508_D003000_D006973   | SUCCESS             | Clonidine is an antihypertensive agent, directly treating hypertension.                                                                                                                                                         |            2 |       0 |
|   3 |        227508 | clonidine                                     | hypotensive                                   | 227508_D003000_D007022   | SUCCESS             | Hypotensive is a physiological effect, not a clinical disease.                                                                                                                                                                  |            0 |       0 |
|   4 |        227508 | nalozone                                      | hypertensive                                  | 227508_None_D006973      | SUCCESS             | Nalozone (likely a typo for naloxone) reverses the antihypertensive effect of clonidine, indicating active antagonism.                                                                                                          |            3 |       0 |
|   5 |        227508 | nalozone                                      | hypotensive                                   | 227508_None_D007022      | SUCCESS             | Hypotensive is a physiological effect, not a clinical disease.                                                                                                                                                                  |            0 |       0 |
|   6 |        227508 | alpha-methyldopa                              | hypertensive                                  | 227508_D008750_D006973   | SUCCESS             | Alpha-methyldopa is an antihypertensive agent, directly treating hypertension.                                                                                                                                                  |            2 |       0 |
|   7 |        227508 | alpha-methyldopa                              | hypotensive                                   | 227508_D008750_D007022   | SUCCESS             | Hypotensive is a physiological effect, not a clinical disease.                                                                                                                                                                  |            0 |       1 |
|   8 |        354896 | lidocaine                                     | cardiac asystole                              | 354896_D008012_D006323   | SUCCESS             | Lidocaine directly caused cardiac asystole through sinoatrial/atrioventricular nodal depression, fulfilling causation criteria.                                                                                                 |            1 |       1 |
|   9 |        354896 | lidocaine                                     | depression                                    | 354896_D008012_D003866   | SUCCESS             | The term 'depression' here refers to mechanical activity reduction (non-pathological polysemy), not a disease state.                                                                                                            |            0 |       0 |
|  10 |        354896 | lidocaine                                     | bradyarrhythmias                              | 354896_D008012_D001919   | SUCCESS             | Lidocaine induced bradyarrhythmias as an adverse effect, meeting causation criteria.                                                                                                                                            |            1 |       0 |
|  11 |        435349 | suxamethonium                                 | fasciculations                                | 435349_D013390_D005207   | SUCCESS             | The text explicitly states that suxamethonium infusion rates directly correlate with fasciculation scores, indicating a causative relationship.                                                                                 |            1 |       1 |
|  12 |        435349 | suxamethonium                                 | tetanic                                       | 435349_D013390_D013746   | SUCCESS             | The term 'tetanic' refers to tetanic stimulation (a physiological test method) rather than a pathological disease state, disqualifying it as a clinical disease entity.                                                         |            0 |       0 |
|  13 |        603022 | galanthamine hydrobromide                     | overdosage                                    | 603022_D005702_D062787   | SUCCESS             | Galanthamine hydrobromide is used to treat central effects caused by scopolamine overdosage, indicating a therapeutic relationship.                                                                                             |            2 |       0 |
|  14 |        603022 | scopolamine                                   | overdosage                                    | 603022_D012601_D062787   | SUCCESS             | Scopolamine (hyoscine) overdosage is the condition being treated by galanthamine, establishing a causal relationship.                                                                                                           |            1 |       1 |
|  15 |        603022 | physostigmine                                 | overdosage                                    | 603022_D010830_D062787   | SUCCESS             | Physostigmine is only compared to galanthamine in duration but not explicitly linked to treating overdosage.                                                                                                                    |            0 |       0 |
|  16 |       1378968 | lithium                                       | chronic renal failure                         | 1378968_D008094_D007676  | SUCCESS             | Lithium induces chronic renal failure as stated in the study design and observed outcomes.                                                                                                                                      |            1 |       1 |
|  17 |       1378968 | lithium                                       | nephropathy                                   | 1378968_D008094_D007674  | SUCCESS             | Lithium directly causes nephropathy as explicitly stated in 'lithium-induced nephropathy'.                                                                                                                                      |            1 |       0 |
|  18 |       1378968 | lithium                                       | renal failure                                 | 1378968_D008094_D051437  | SUCCESS             | Lithium causes renal failure through GFR reduction and other pathological changes.                                                                                                                                              |            1 |       0 |
|  19 |       1378968 | lithium                                       | proteinuria                                   | 1378968_D008094_D011507  | SUCCESS             | Lithium induces proteinuria as a direct effect mentioned in the text.                                                                                                                                                           |            1 |       1 |
|  20 |       1378968 | lithium                                       | hypertension                                  | 1378968_D008094_D006973  | SUCCESS             | Lithium causes systolic hypertension as explicitly stated in the results.                                                                                                                                                       |            1 |       1 |
|  21 |       1378968 | lithium                                       | glomerulosclerosis                            | 1378968_D008094_D005921  | SUCCESS             | No evidence lithium causes glomerulosclerosis; text states 'absence of glomerulosclerosis'.                                                                                                                                     |            0 |       0 |
|  22 |       1378968 | creatinine                                    | chronic renal failure                         | 1378968_D003404_D007676  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to chronic renal failure.                                                                                                                                     |            0 |       0 |
|  23 |       1378968 | creatinine                                    | nephropathy                                   | 1378968_D003404_D007674  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to nephropathy.                                                                                                                                               |            0 |       0 |
|  24 |       1378968 | creatinine                                    | renal failure                                 | 1378968_D003404_D051437  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to renal failure.                                                                                                                                             |            0 |       0 |
|  25 |       1378968 | creatinine                                    | proteinuria                                   | 1378968_D003404_D011507  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to proteinuria.                                                                                                                                               |            0 |       0 |
|  26 |       1378968 | creatinine                                    | hypertension                                  | 1378968_D003404_D006973  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to hypertension.                                                                                                                                              |            0 |       0 |
|  27 |       1378968 | creatinine                                    | glomerulosclerosis                            | 1378968_D003404_D005921  | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to glomerulosclerosis.                                                                                                                                        |            0 |       0 |
|  28 |       1420741 | fusidic acid                                  | crohn's disease                               | 1420741_D005672_D003424  | SUCCESS             | Fusidic acid was administered to treat chronic active Crohn's disease in therapy-resistant patients, with 63% showing improvement, indicating a therapeutic relationship.                                                       |            2 |       0 |
|  29 |       1420741 | fusidic acid                                  | nausea                                        | 1420741_D005672_D009325  | SUCCESS             | Nausea occurred in two patients during fusidic acid treatment, necessitating dose reduction, indicating an adverse effect.                                                                                                      |            1 |       1 |
|  30 |       1420741 | fusidic acid                                  | inflammatory bowel disease                    | 1420741_D005672_D015212  | SUCCESS             | The text suggests a scientific rationale for fusidic acid's use in IBD at the cytokine level but does not explicitly state treatment of IBD as a disease entity.                                                                |            0 |       0 |
|  31 |       1420741 | cyclosporin                                   | crohn's disease                               | 1420741_D016572_D003424  | SUCCESS             | Cyclosporin is mentioned as a drug with similar immunosuppressive effects to fusidic acid, but no explicit treatment claim for Crohn's disease is made in the text.                                                             |            0 |       0 |
|  32 |       1420741 | cyclosporin                                   | nausea                                        | 1420741_D016572_D009325  | SUCCESS             | No mention of cyclosporin causing or relating to nausea in the text.                                                                                                                                                            |            0 |       0 |
|  33 |       1420741 | cyclosporin                                   | inflammatory bowel disease                    | 1420741_D016572_D015212  | SUCCESS             | Cyclosporin's immunosuppressive properties are referenced, but no explicit treatment claim for IBD is stated in the text.                                                                                                       |            0 |       0 |
|  34 |       1601297 | cocaine                                       | myocardial injury                             | 1601297_D003042_D009202  | SUCCESS             | The text reports an association between cocaine use and ECG evidence of myocardial injury, but does not explicitly state causation.                                                                                             |            0 |       0 |
|  35 |       1601297 | cocaine                                       | schizophrenic                                 | 1601297_D003042_D012559  | SUCCESS             | The term 'schizophrenic' is an adjective describing the control group, not a disease pathology in this context.                                                                                                                 |            0 |       0 |
|  36 |       1601297 | cocaine                                       | myocardial infarction                         | 1601297_D003042_D009203  | SUCCESS             | The study notes myocardial infarction as part of observed injuries but does not assert direct causation by cocaine.                                                                                                             |            0 |       1 |
|  37 |       1601297 | cocaine                                       | ischemia                                      | 1601297_D003042_D007511  | SUCCESS             | Ischemia is listed as an observed ECG finding but no explicit causal link to cocaine is stated.                                                                                                                                 |            0 |       0 |
|  38 |       1601297 | cocaine                                       | bundle branch block                           | 1601297_D003042_D002037  | SUCCESS             | Bundle branch block is mentioned as part of the injury criteria but no causative relationship is explicitly declared.                                                                                                           |            0 |       1 |
|  39 |       1967484 | sulpiride                                     | tardive dystonia                              | 1967484_D013469_D004421  | SUCCESS             | The text explicitly states 'Sulpiride-induced tardive dystonia', establishing a direct causal relationship.                                                                                                                     |            1 |       1 |
|  40 |       1967484 | sulpiride                                     | tardive dyskinesia                            | 1967484_D013469_D004409  | SUCCESS             | The text reports 'sulpiride-induced tardive dyskinesia' as an occasionally observed side effect.                                                                                                                                |            1 |       0 |
|  41 |       1967484 | sulpiride                                     | parkinsonism                                  | 1967484_D013469_D010302  | SUCCESS             | The text explicitly mentions 'sulpiride-induced parkinsonism' as an occasionally reported effect.                                                                                                                               |            1 |       0 |
|  42 |       1967484 | antidepressant                                | tardive dystonia                              | 1967484_D000928_D004421  | SUCCESS             | No direct relationship between 'antidepressant' and 'tardive dystonia' is stated; 'antidepressant' is a property of sulpiride, not an independent agent.                                                                        |            0 |       0 |
|  43 |       1967484 | antidepressant                                | tardive dyskinesia                            | 1967484_D000928_D004409  | SUCCESS             | No explicit link between 'antidepressant' and 'tardive dyskinesia' is provided in the text.                                                                                                                                     |            0 |       0 |
|  44 |       1967484 | antidepressant                                | parkinsonism                                  | 1967484_D000928_D010302  | SUCCESS             | No causal or therapeutic relationship between 'antidepressant' and 'parkinsonism' is stated.                                                                                                                                    |            0 |       0 |

In [ ]:
df_final_eval = pd.merge(
    relationship_dataset["train"].to_pandas(), # Your original evaluation dataframe with the 'label' column
    checkpoint_df,
    on=['document_id', 'chemical', 'disease'],
    how='left'
)

print(df_final_eval[subset].dropna().to_markdown())

|     |   document_id | chemical                  | disease                                   | id                      | extraction_status   | chain_of_thought                                                                                                                                                                                                        |   weak_label |   label |
|----:|--------------:|:--------------------------|:------------------------------------------|:------------------------|:--------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------:|--------:|
|   8 |        354896 | lidocaine                 | cardiac asystole                          | 354896_D008012_D006323  | SUCCESS             | Lidocaine directly caused cardiac asystole through sinoatrial/atrioventricular nodal depression, fulfilling causation criteria.                                                                                         |            1 |       1 |
|   9 |        354896 | lidocaine                 | depression                                | 354896_D008012_D003866  | SUCCESS             | The term 'depression' here refers to mechanical activity reduction (non-pathological polysemy), not a disease state.                                                                                                    |            0 |       0 |
|  10 |        354896 | lidocaine                 | bradyarrhythmias                          | 354896_D008012_D001919  | SUCCESS             | Lidocaine induced bradyarrhythmias as an adverse effect, meeting causation criteria.                                                                                                                                    |            1 |       0 |
|  11 |        435349 | suxamethonium             | fasciculations                            | 435349_D013390_D005207  | SUCCESS             | The text explicitly states that suxamethonium infusion rates directly correlate with fasciculation scores, indicating a causative relationship.                                                                         |            1 |       1 |
|  12 |        435349 | suxamethonium             | tetanic                                   | 435349_D013390_D013746  | SUCCESS             | The term 'tetanic' refers to tetanic stimulation (a physiological test method) rather than a pathological disease state, disqualifying it as a clinical disease entity.                                                 |            0 |       0 |
|  13 |        603022 | galanthamine hydrobromide | overdosage                                | 603022_D005702_D062787  | SUCCESS             | Galanthamine hydrobromide is used to treat central effects caused by scopolamine overdosage, indicating a therapeutic relationship.                                                                                     |            2 |       0 |
|  14 |        603022 | scopolamine               | overdosage                                | 603022_D012601_D062787  | SUCCESS             | Scopolamine (hyoscine) overdosage is the condition being treated by galanthamine, establishing a causal relationship.                                                                                                   |            1 |       1 |
|  15 |        603022 | physostigmine             | overdosage                                | 603022_D010830_D062787  | SUCCESS             | Physostigmine is only compared to galanthamine in duration but not explicitly linked to treating overdosage.                                                                                                            |            0 |       0 |
|  16 |       1378968 | lithium                   | chronic renal failure                     | 1378968_D008094_D007676 | SUCCESS             | Lithium induces chronic renal failure as stated in the study design and observed outcomes.                                                                                                                              |            1 |       1 |
|  17 |       1378968 | lithium                   | nephropathy                               | 1378968_D008094_D007674 | SUCCESS             | Lithium directly causes nephropathy as explicitly stated in 'lithium-induced nephropathy'.                                                                                                                              |            1 |       0 |
|  18 |       1378968 | lithium                   | renal failure                             | 1378968_D008094_D051437 | SUCCESS             | Lithium causes renal failure through GFR reduction and other pathological changes.                                                                                                                                      |            1 |       0 |
|  19 |       1378968 | lithium                   | proteinuria                               | 1378968_D008094_D011507 | SUCCESS             | Lithium induces proteinuria as a direct effect mentioned in the text.                                                                                                                                                   |            1 |       1 |
|  20 |       1378968 | lithium                   | hypertension                              | 1378968_D008094_D006973 | SUCCESS             | Lithium causes systolic hypertension as explicitly stated in the results.                                                                                                                                               |            1 |       1 |
|  21 |       1378968 | lithium                   | glomerulosclerosis                        | 1378968_D008094_D005921 | SUCCESS             | No evidence lithium causes glomerulosclerosis; text states 'absence of glomerulosclerosis'.                                                                                                                             |            0 |       0 |
|  22 |       1378968 | creatinine                | chronic renal failure                     | 1378968_D003404_D007676 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to chronic renal failure.                                                                                                                             |            0 |       0 |
|  23 |       1378968 | creatinine                | nephropathy                               | 1378968_D003404_D007674 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to nephropathy.                                                                                                                                       |            0 |       0 |
|  24 |       1378968 | creatinine                | renal failure                             | 1378968_D003404_D051437 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to renal failure.                                                                                                                                     |            0 |       0 |
|  25 |       1378968 | creatinine                | proteinuria                               | 1378968_D003404_D011507 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to proteinuria.                                                                                                                                       |            0 |       0 |
|  26 |       1378968 | creatinine                | hypertension                              | 1378968_D003404_D006973 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to hypertension.                                                                                                                                      |            0 |       0 |
|  27 |       1378968 | creatinine                | glomerulosclerosis                        | 1378968_D003404_D005921 | SUCCESS             | Creatinine is a biomarker, not a causal agent; no direct relation to glomerulosclerosis.                                                                                                                                |            0 |       0 |
|  28 |       1420741 | fusidic acid              | crohn's disease                           | 1420741_D005672_D003424 | SUCCESS             | Fusidic acid was administered to treat chronic active Crohn's disease in therapy-resistant patients, with 63% showing improvement, indicating a therapeutic relationship.                                               |            2 |       0 |
|  29 |       1420741 | fusidic acid              | nausea                                    | 1420741_D005672_D009325 | SUCCESS             | Nausea occurred in two patients during fusidic acid treatment, necessitating dose reduction, indicating an adverse effect.                                                                                              |            1 |       1 |
|  30 |       1420741 | fusidic acid              | inflammatory bowel disease                | 1420741_D005672_D015212 | SUCCESS             | The text suggests a scientific rationale for fusidic acid's use in IBD at the cytokine level but does not explicitly state treatment of IBD as a disease entity.                                                        |            0 |       0 |
|  31 |       1420741 | cyclosporin               | crohn's disease                           | 1420741_D016572_D003424 | SUCCESS             | Cyclosporin is mentioned as a drug with similar immunosuppressive effects to fusidic acid, but no explicit treatment claim for Crohn's disease is made in the text.                                                     |            0 |       0 |
|  32 |       1420741 | cyclosporin               | nausea                                    | 1420741_D016572_D009325 | SUCCESS             | No mention of cyclosporin causing or relating to nausea in the text.                                                                                                                                                    |            0 |       0 |
|  33 |       1420741 | cyclosporin               | inflammatory bowel disease                | 1420741_D016572_D015212 | SUCCESS             | Cyclosporin's immunosuppressive properties are referenced, but no explicit treatment claim for IBD is stated in the text.                                                                                               |            0 |       0 |
|  34 |       1601297 | cocaine                   | myocardial injury                         | 1601297_D003042_D009202 | SUCCESS             | The text reports an association between cocaine use and ECG evidence of myocardial injury, but does not explicitly state causation.                                                                                     |            0 |       0 |
|  35 |       1601297 | cocaine                   | schizophrenic                             | 1601297_D003042_D012559 | SUCCESS             | The term 'schizophrenic' is an adjective describing the control group, not a disease pathology in this context.                                                                                                         |            0 |       0 |
|  36 |       1601297 | cocaine                   | myocardial infarction                     | 1601297_D003042_D009203 | SUCCESS             | The study notes myocardial infarction as part of observed injuries but does not assert direct causation by cocaine.                                                                                                     |            0 |       1 |
|  37 |       1601297 | cocaine                   | ischemia                                  | 1601297_D003042_D007511 | SUCCESS             | Ischemia is listed as an observed ECG finding but no explicit causal link to cocaine is stated.                                                                                                                         |            0 |       0 |
|  38 |       1601297 | cocaine                   | bundle branch block                       | 1601297_D003042_D002037 | SUCCESS             | Bundle branch block is mentioned as part of the injury criteria but no causative relationship is explicitly declared.                                                                                                   |            0 |       1 |
|  39 |       1967484 | sulpiride                 | tardive dystonia                          | 1967484_D013469_D004421 | SUCCESS             | The text explicitly states 'Sulpiride-induced tardive dystonia', establishing a direct causal relationship.                                                                                                             |            1 |       1 |
|  40 |       1967484 | sulpiride                 | tardive dyskinesia                        | 1967484_D013469_D004409 | SUCCESS             | The text reports 'sulpiride-induced tardive dyskinesia' as an occasionally observed side effect.                                                                                                                        |            1 |       0 |
|  41 |       1967484 | sulpiride                 | parkinsonism                              | 1967484_D013469_D010302 | SUCCESS             | The text explicitly mentions 'sulpiride-induced parkinsonism' as an occasionally reported effect.                                                                                                                       |            1 |       0 |
|  42 |       1967484 | antidepressant            | tardive dystonia                          | 1967484_D000928_D004421 | SUCCESS             | No direct relationship between 'antidepressant' and 'tardive dystonia' is stated; 'antidepressant' is a property of sulpiride, not an independent agent.                                                                |            0 |       0 |
|  43 |       1967484 | antidepressant            | tardive dyskinesia                        | 1967484_D000928_D004409 | SUCCESS             | No explicit link between 'antidepressant' and 'tardive dyskinesia' is provided in the text.                                                                                                                             |            0 |       0 |
|  44 |       1967484 | antidepressant            | parkinsonism                              | 1967484_D000928_D010302 | SUCCESS             | No causal or therapeutic relationship between 'antidepressant' and 'parkinsonism' is stated.                                                                                                                            |            0 |       0 |
|  45 |       2234245 | desferrioxamine           | ocular and auditory toxicity              | 2234245_D003676_D014786 | SUCCESS             | Desferrioxamine induces ocular and auditory toxicity as evidenced by clinical symptoms and reversibility upon drug withdrawal.                                                                                          |            1 |       1 |
|  46 |       2234245 | desferrioxamine           | auditory toxicity                         | 2234245_D003676_D006311 | SUCCESS             | Desferrioxamine induces auditory toxicity characterized by neurosensorial hearing loss, confirmed by reversibility after discontinuation.                                                                               |            1 |       0 |
|  47 |       2234245 | desferrioxamine           | dyschromatopsy                            | 2234245_D003676_None    | SUCCESS             | Desferrioxamine causes dyschromatopsy as a component of retinal toxicity, directly described in the text.                                                                                                               |            1 |       0 |
|  48 |       2234245 | desferrioxamine           | pigmentary retinal deposits               | 2234245_D003676_D012164 | SUCCESS             | Desferrioxamine induces pigmentary retinal deposits as part of its visual toxicity profile.                                                                                                                             |            1 |       1 |
|  50 |       2234245 | desferrioxamine           | hearing loss                              | 2234245_D003676_D034381 | SUCCESS             | Desferrioxamine induces hearing loss as part of its auditory toxicity profile.                                                                                                                                          |            1 |       0 |
|  51 |       2234245 | desferrioxamine           | toxicity                                  | 2234245_D003676_D064420 | SUCCESS             | Desferrioxamine causes general toxicity (audiovisual) as a documented adverse effect requiring monitoring.                                                                                                              |            1 |       0 |
|  52 |       2234245 | aluminium                 | ocular and auditory toxicity              | 2234245_None_D014786    | SUCCESS             | Aluminium serum levels correlate with toxicity onset but do not directly cause ocular/auditory toxicity per the text.                                                                                                   |            0 |       0 |
|  53 |       2234245 | aluminium                 | auditory toxicity                         | 2234245_None_D006311    | SUCCESS             | Aluminium levels are temporally associated with auditory toxicity but not causally linked per the text.                                                                                                                 |            0 |       0 |
|  54 |       2234245 | aluminium                 | dyschromatopsy                            | 2234245_None_None       | SUCCESS             | Aluminium serum levels are mentioned but not shown to cause dyschromatopsy.                                                                                                                                             |            0 |       0 |
|  55 |       2234245 | aluminium                 | pigmentary retinal deposits               | 2234245_None_D012164    | SUCCESS             | Aluminium levels are temporally associated but not causally linked to pigmentary retinal deposits.                                                                                                                      |            0 |       0 |
|  57 |       2234245 | aluminium                 | hearing loss                              | 2234245_None_D034381    | SUCCESS             | Aluminium levels are temporally associated with toxicity but not causally linked to hearing loss.                                                                                                                       |            0 |       0 |
|  58 |       2234245 | aluminium                 | toxicity                                  | 2234245_None_D064420    | SUCCESS             | Aluminium serum levels are mentioned as a temporal correlate but not a direct cause of toxicity.                                                                                                                        |            0 |       0 |

In [32]:
checkpoint_df

,document_id,extraction_status,chemical,disease,chain_of_thought,weak_label
0,227508,FAILED: Error code: 400 - {'error': {'message'...,None,None,None,None
1,354896,SUCCESS,lidocaine,cardiac asystole,Lidocaine directly caused cardiac asystole thr...,1
2,354896,SUCCESS,lidocaine,depression,The term 'depression' here refers to mechanica...,0
3,354896,SUCCESS,lidocaine,bradyarrhythmias,Lidocaine induced bradyarrhythmias as an adver...,1
4,435349,SUCCESS,suxamethonium,fasciculations,The text explicitly states that suxamethonium ...,1
...,...,...,...,...,...,...
107,3409645,SUCCESS,methotrexate,rheumatoid arthritis,No explicit therapeutic or causal link between...,0
108,3409645,SUCCESS,methotrexate,osteoarthritis,No explicit therapeutic or causal link between...,0
109,3409645,SUCCESS,methotrexate,spondyloarthropathy,No explicit therapeutic or causal link between...,0
110,3409645,SUCCESS,methotrexate,depressed mood,No explicit causal or therapeutic link between...,0
111,3409645,SUCCESS,methotrexate,impotence,Methotrexate is associated with impotence as a...,1

In [33]:
relationship_dataset["train"].to_pandas()

,document_id,chemical,disease,chemical_id,disease_id,masked_text,label,id
0,227508,naloxone,hypertensive,D009270,D006973,<chemical> Naloxone </chemical> reverses the a...,0,227508_D009270_D006973
1,227508,naloxone,hypotensive,D009270,D007022,<chemical> Naloxone </chemical> reverses the a...,0,227508_D009270_D007022
2,227508,clonidine,hypertensive,D003000,D006973,Naloxone reverses the antihypertensive effect ...,0,227508_D003000_D006973
3,227508,clonidine,hypotensive,D003000,D007022,Naloxone reverses the antihypertensive effect ...,0,227508_D003000_D007022
4,227508,nalozone,hypertensive,None,D006973,Naloxone reverses the antihypertensive effect ...,0,227508_None_D006973
...,...,...,...,...,...,...,...,...
5510,10683478,dopamine,hyperactivity,D004298,D006948,Test conditions influence the response to a dr...,0,10683478_D004298_D006948
5511,10683478,dopac,hypothermia,D015102,D007035,Test conditions influence the response to a dr...,0,10683478_D015102_D007035
5512,10683478,dopac,hyperactivity,D015102,D006948,Test conditions influence the response to a dr...,0,10683478_D015102_D006948
5513,10683478,hva,hypothermia,D006719,D007035,Test conditions influence the response to a dr...,0,10683478_D006719_D007035
5514,10683478,hva,hyperactivity,D006719,D006948,Test conditions influence the response to a dr...,0,10683478_D006719_D006948